# Generated by Django 5.0.6 on 2024-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=1000)),
                ('winner', models.CharField(max_length=10)),
                ('policy', models.TextField(max_length=1000)),
            ],
        ),
    ]
